version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: srmonitor
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  core:
    build:
      context: ./core
    env_file:
      - .env  # <-- Pfad korrekt, weil .env im selben Verzeichnis wie docker-compose.yml
    volumes:
      - ./core/localhost+2.pem:/app/localhost+2.pem:ro
      - ./core/localhost+2-key.pem:/app/localhost+2-key.pem:ro
    command: >
      uvicorn app:app --host 0.0.0.0 --port 8000
      --ssl-keyfile /app/localhost+2-key.pem
      --ssl-certfile /app/localhost+2.pem
    ports:
      - "8000:8000"
    working_dir: /app
    depends_on:
      - db
    networks:
      - app-network

  agent:
    build:
      context: ./agent
    environment:
      SHELLY_IP: 172.20.10.4
      CORE_ENDPOINT: https://core:8000/api/shelly
    depends_on:
      - core
      - simulator
    networks:
      - app-network

  simulator:
    build:
      context: ./simulator
    ports:
      - "8080:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/localhost+2.pem:/app/localhost+2.pem:ro
      - ./frontend/localhost+2-key.pem:/app/localhost+2-key.pem:ro
    depends_on:
      - core
    ports:
      - "3000:3000"
    command: >
      npx serve dist
        -l 3000
        --ssl-cert /app/localhost+2.pem
        --ssl-key /app/localhost+2-key.pem
    networks:
      - app-network

  ticket-service:
    build:
      context: ./ticket-service
    ports:
    - "5001:5001"
    volumes:
    - ticket-data:/app/data
    - ./ticket-service/localhost+2.pem:/app/localhost+2.pem:ro
    - ./ticket-service/localhost+2-key.pem:/app/localhost+2-key.pem:ro
    env_file:
    - .env
    command: >
      uvicorn app:app --host 0.0.0.0 --port 5001
      --ssl-keyfile /app/localhost+2-key.pem
      --ssl-certfile /app/localhost+2.pem
    networks:
    - app-network

volumes:
  db-data:
  ticket-data:

networks:
  app-network:
    driver: bridge
