version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: srmonitor
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  core:
    build:
      context: ./core
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network

  simulator:
    build:
      context: ./simulator
    ports:
      - "8080:80"
    networks:
      - app-network

  agent:
    build:
      context: ./agent
    environment:
      SHELLY_IP: simulator
      CORE_ENDPOINT: http://core:8000/api/shelly
    depends_on:
      - core
      - simulator
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/localhost+2.pem:/app/localhost+2.pem:ro
      - ./frontend/localhost+2-key.pem:/app/localhost+2-key.pem:ro
    depends_on:
      - core
    ports:
      - "3000:3000"
    command: >
      npx serve dist
        -l 3000
        --ssl-cert /app/localhost+2.pem
        --ssl-key /app/localhost+2-key.pem
    networks:
      - app-network

  ticket-service:
    build:
      context: ./ticket-service
    ports:
      - "5000:5000"
    volumes:
      - ticket-data:/app/data
    networks:
      - app-network

volumes:
  db-data:
  ticket-data:

networks:
  app-network:
    driver: bridge
